trigger:
  branches:
    include:
      - main  # Specify the branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'nodeapp'  # Docker image repository name
  tag: '$(Build.BuildId)'  # Use Build.BuildId for tagging the image

steps:
# Install Node.js and dependencies
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    npm install
    npm run build  # Optional if your app has a build step
  displayName: 'Install dependencies and build the app'

# Build and push Docker image to Azure Container Registry (ACR)
- task: Docker@2
  displayName: 'Build and Push Docker image to ACR'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'  # ACR connection
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)

# Deploy to Azure App Service using the image built
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: '$(azureSubscriptionConnection)'  # Azure Resource Manager connection
    appName: 'your-app-service-name'  # Azure App Service name
    containerRegistry: '$(dockerRegistryServiceConnection)'
    imageName: '$(imageName)'
    tag: '$(tag)'  # Deploy the image tagged with Build.BuildId
