trigger:
  branches:
    include:
      - main  # Adjust based on your main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'provincemanagmentqa.azurecr.io' # Set this up in Azure DevOps
  imageRepository: 'main'  # Your Docker repository name
  containerRegistry: 'provincemanagmentqa.azurecr.io/myapp' # Docker Hub or Azure Container Registry (ACR)
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageRepository)'
      command: 'buildAndPush'
      Dockerfile: '$(dockerfilePath)'
      tags: |
        $(tag)

  - script: echo "Docker image built and pushed successfully."
